name: Schedule Packer automatic image build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  ARM_USE_AZUREAD: true
  ARM_USE_OIDC: true
  PACKER_VERSION: "latest"
  WORKING_DIR: ./src

jobs:
  terraform-deploy:
    name: Deploy Infrastructure
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    #   - name: Azure Login with OIDC
    #     uses: azure/login@v2
    #     with:
    #       client-id: ${{ env.ARM_CLIENT_ID }}
    #       tenant-id: ${{ env.ARM_TENANT_ID }}
    #       subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ vars.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}"

      - name: Terraform Format and Validate
        run: |
          terraform fmt -check
          terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file="./dev.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  packer-build:
    name: Build VM Image
    environment: dev
    runs-on: ubuntu-latest
    needs: terraform-deploy
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Packer Initialize
        run: packer init ./az-windows-11-ent.pkr.hcl

      - name: Packer Validate
        run: packer validate ./az-windows-11-ent.pkr.hcl

      - name: Packer Build
        run: packer build ./az-windows-11-ent.pkr.hcl
